# https://docs.python-guide.org/scenarios/scrape/
from lxml import html
import requests

# Maybe later I'll formalize this process more.
def gen_atoz():
    page = requests.get('http://www.catalog.gatech.edu/coursesaz/')
    tree = html.fromstring(page.content)
    atozindex = tree.xpath("//div[@id='atozindex']/ul/li/a/text()") # https://www.w3schools.com/xml/xpath_syntax.asp
    atozdict = {i[i.index('(')+1:len(i)-1]: i[0:i.index('(')] for i in atozindex} # format list into dictionary
    return atozdict

# generated from gen_AtoZ() on Nov 24, 2020
AtoZ = {'ACCT': 'Accounting ', 'AE': 'Aerospace Engineering ', 'AS': 'Air Force Aerospace Studies ', 'APPH': 'Applied Physiology ', 'ASE': 'Applied Systems Engineering ', 'ARBC': 'Arabic ', 'ARCH': 'Architecture ', 'BIOS': 'Biological Sciences ', 'BIOL': 'Biology ', 'BMEJ': 'Biomed Engr/Joint Emory PKU ', 'BMED': 'Biomedical Engineering ', 'BMEM': 'Biomedical Engr/Joint Emory ', 'BC': 'Building Construction ', 'BCP': 'Building Construction - Professional ', 'CETL': 'Center Enhancement-Teach/Learn ', 'CHBE': 'Chemical & Biomolecular Engr ', 'CHEM': 'Chemistry ', 'CHIN': 'Chinese ', 'CP': 'City Planning ', 'CEE': 'Civil and Environmental Engr ', 'COA': 'College of Architecture ', 'COE': 'College of Engineering ', 'COS': 'College of Sciences ', 'CX': 'Computational Mod, Sim, & Data ', 'CSE': 'Computational Science & Engr ', 'CS': 'Computer Science ', 'COOP': 'Cooperative Work Assignment ', 'UCGA': 'Cross Enrollment ', 'EAS': 'Earth and Atmospheric Sciences ', 'ECON': 'Economics ', 'ECEP': 'Elect & Comp Engr-Professional ', 'ECE': 'Electrical & Computer Engr ', 'ENGL': 'English ', 'FS': 'Foreign Studies ', 'FREE': 'Free Elective ', 'FREN': 'French ', 'GT': 'Georgia Tech ', 'GTL': 'Georgia Tech Lorraine ', 'GRMN': 'German ', 'HP': 'Health Physics ', 'HS': 'Health Systems ', 'HEBW': 'Hebrew ', 'HIN': 'Hindi ', 'HIST': 'History ', 'HTS': 'History, Technology & Society ', 'HUM': 'Humanities Elective ', 'ID': 'Industrial Design ', 'ISYE': 'Industrial & Systems Engr ', 'INTA': 'International Affairs ', 'IL': 'International Logistics ', 'INTN': 'Internship ', 'IMBA': 'Intl Executive MBA ', 'IPCO': "Int'l Plan Co-op Abroad ", 'IPFS': "Int'l Plan-Exchange Prgm ", 'IPIN': "Int'l Plan Intern Abroad ", 'IPSA': "Int'l Plan-Study Abroad ", 'IAC': 'Ivan Allen College ', 'JAPN': 'Japanese ', 'KOR': 'Korean ', 'LATN': 'Latin ', 'LS': 'Learning Support ', 'LING': 'Linguistics ', 'LMC': 'Literature, Media & Comm ', 'MGT': 'Management ', 'MOT': 'Management of Technology ', 'MLDR': 'Manufacturing Leadership ', 'MSE': 'Materials Science & Engr ', 'MATH': 'Mathematics ', 'ME': 'Mechanical Engineering ', 'MP': 'Medical Physics ', 'MSL': 'Military Science & Leadership ', 'ML': 'Modern Languages ', 'MUSI': 'Music ', 'NS': 'Naval Science ', 'NEUR': 'Neuroscience ', 'NRE': 'Nuclear & Radiological Engr ', 'PERS': 'Persian ', 'PHIL': 'Philosophy ', 'PHYS': 'Physics ', 'POL': 'Political Science ', 'PTFE': 'Polymer, Textile and Fiber Eng ', 'DOPP': 'Professional Practive ', 'PSYC': 'Psychology ', 'PUBJ': 'Public Policy/Joint GSU PhD ', 'PUBP': 'Public Policy ', 'RUSS': 'Russian ', 'SCI': 'Science ', 'SLS': 'Serve Learn Sustain ', 'SS': 'Social Science Elective ', 'SOC': 'Sociology ', 'SPAN': 'Spanish ', 'SWAH': 'Swahili '}
